### ISSUE TITLE
Flutter web hover issue

### ISSUE THREAD

**Issue by shutdown-s** [AbdullahChauhan/custom-dropdown#10]
I tried to override mouse cursor by using `MouseRegion( cursor: SystemMouseCursors.click, child: CustomDropdown.search()...
)` to click for web development but was unsuccessful. Is it possible to change this so that we can edit pointer to click when use hovers dropdown while using browser ?

**Comment by AbdullahChauhan** [comment]
@shutdown-s 
Few days ago, I release 2.0.0. Can you check and confirm if this issue is resolve now?

**Comment by shutdown-s** [comment]
I have tested now and can confirm the issue is fixed.

**Comment by AbdullahChauhan** [comment]
@shutdown-s Thanks :thumbsup:
