### ISSUE TITLE
Need to say it

### ISSUE THREAD

**Issue by marcobraghim** [AbdullahChauhan/custom-dropdown#15]
Thank you. This is the best dropdown menu I ever seen with Flutter. The default Dropdown is really horrible, you did very well.

**Comment by AbdullahChauhan** [comment]
@marcobraghim **Thanks for your kind words, much appreciated :blue_heart:**. 

Yeah, same feelings about the default one. 
Hopefully, I'll get some time to come back and complete my remaining work for this package!
