### ISSUE TITLE
How to change the height?

### ISSUE THREAD

**Issue by ledesmac96** [AbdullahChauhan/custom-dropdown#17]
I can't change the height of the widget. It is not possible to do it with SizedBox.

**Comment by AbdullahChauhan** [comment]
Hey @ledesmac96 
No, you can't specify the dropdown height. But I'm thinking about to make this property available in future release!

**Comment by justjew** [comment]
Still can't set height. Wrapping in SizedBox also not working.

**Comment by angela-boyadjian** [comment]
Hello, do you plan on adding this property ?

**Comment by AbdullahChauhan** [comment]
Hey @angela-boyadjian 
Property `overlayHeight` is already available. Only applicable if items are greater than 4 otherwise adjust automatically.
Let me know if this is not helpful for you!

**Comment by syedumair043** [comment]
@justjew you can wrap it in container and give it the least height 51
