### ISSUE TITLE
Setting initial value

### ISSUE THREAD

**Issue by JesusHdez960717** [AbdullahChauhan/custom-dropdown#18]
I have an implementation of this package as:
```dart
        CustomDropdown.searchRequest(
          items: [some items],
          futureRequest: futureRequest,
          hintText: 'Search something...',
          controller: _controllerForText,
          onChanged: (selected) {
            //some logic...
          },
        ),
```
It work perfect, but...
How can I specify the selected item, for example, when editing some model, I start the view with every field fill with the current value, how do I put the value corresponding to this dropdown.
Or if I have one dropdown that depend on other, B depend on A, when I select a item in A, B is updated with the info, and I update the view, but if I update the view A loose the selected item.

In defaults dropdown, there is a property 'value' with this function, what is the equivalent of this property in this package?

This is the one how worked for my:
```dart
DropdownButtonHideUnderline(
          child: DropdownButton<String>(
            hint: Text(
              'Select type',
              style: TextStyle(
                fontSize: 14,
                color: Theme.of(context).hintColor,
              ),
            ),
            items: items
                .map(
                  (item) => DropdownMenuItem<String>(
                    value: item,
                    child: Text(
                      item,
                      style: const TextStyle(
                        fontSize: 14,
                      ),
                    ),
                  ),
                )
                .toList(),
            value: initialValue, //this property is what I need
            onChanged: (value) {
              //some logic
            },
          ),
        )
```

**Comment by AbdullahChauhan** [comment]
Hey @JesusHdez960717 Thanks for asking.

You can specify your initial value or changing state value by using controller. 
`final dataCtrl = TextEditingController(text: data)`

Now, that `data` variable for controller text can hold your initial value or also the updated state[data] value. So in your case, when your model is ready for view, you can assign the value to controller so that dropdown knows something is passed as initial value.

I hope I answered your question, Thanks!

**Comment by JesusHdez960717** [comment]
Thanks @AbdullahChauhan, your solution work perfectly. 
An amazing package, great work.
👍🏻
