### ISSUE TITLE
error: disallowIndicator() method does not exists

### ISSUE THREAD

**Issue by devmuaz** [AbdullahChauhan/custom-dropdown#2]
Error found in `dropdown_overlay.dart` file, line `159`
```
Error: The method 'disallowIndicator' isn't defined for the class 'OverscrollIndicatorNotification'.
Try correcting the name to the name of an existing method, or defining a method named 'disallowIndicator'.notification.disallowIndicator();
```

Solution:
I believe replacing the `disallowIndicator()` with `disallowGlow()` solves the problem!

**Comment by AbdullahChauhan** [comment]
> Error found in `dropdown_overlay.dart` file, line `159`
> 
> ```
> Error: The method 'disallowIndicator' isn't defined for the class 'OverscrollIndicatorNotification'.
> Try correcting the name to the name of an existing method, or defining a method named 'disallowIndicator'.notification.disallowIndicator();
> ```
> 
> Solution: I believe replacing the `disallowIndicator()` with `disallowGlow()` solves the problem!

@devmuaz 
The latest release is built on Flutter version 2.8 where `disallowGlow()` was deprecated in favor of `disallowIndicator()`.

**Comment by devmuaz** [comment]
@AbdullahChauhan well, that's seems to be correct since im still using v2.5.1 due to some crashing issues related to v2.8!

Thanks 😄
