### ISSUE TITLE
Show full text in menu display

### ISSUE THREAD

**Issue by NueveSeis** [AbdullahChauhan/custom-dropdown#22]
How can I display the full text of the item, try something like: TextStyle(overflow: TextOverflow.visible). But help does not work, my text is 70 characters and I have several of that size. I want to display the full text when the menu is displayed

**Comment by AbdullahChauhan** [comment]
Hi @NueveSeis Can you kindly share the screenshot of your situation so I can better understand what's happening!

**Comment by NueveSeis** [comment]
Hello, what I was referring to was showing the full text in a dropdownButtonFormField as in image 1. It's because your component doesn't display the full text in image 2. I also don't know if there is a way to display the full text in the field without having to slide as in image 3. And finally, there is no way to change the text of search and not found ?  picture 4.

Image 1
![Screenshot_2023-05-07-08-32-42-05_016d12511025108972fc2884789002e0~2.jpg](https://user-images.githubusercontent.com/53452426/236684312-92e55cb1-c524-4b67-8c11-3f34a26e12d0.jpg)


Image 2
![Screenshot_2023-05-07-08-32-52-55_016d12511025108972fc2884789002e0~2.jpg](https://user-images.githubusercontent.com/53452426/236684333-a379dbde-bccc-43c1-9c2b-65611b2dc419.jpg)



Image 3
![Screenshot_2023-05-07-08-32-56-49_016d12511025108972fc2884789002e0~2.jpg](https://user-images.githubusercontent.com/53452426/236684347-f3343fbd-aa92-42fe-aab2-1cc3270c605c.jpg)


Image 4
![Screenshot_2023-05-07-08-33-10-02_016d12511025108972fc2884789002e0~2.jpg](https://user-images.githubusercontent.com/53452426/236684354-185f57b2-a05b-4a82-8cb2-f70379b4d95e.jpg)

**Comment by AbdullahChauhan** [comment]
Hey @NueveSeis Thanks for pointing these issues. I'll check these...

**Comment by AbdullahChauhan** [comment]
Now available in `2.0.0`. Thanks :+1:
