### ISSUE TITLE
Feature** Will be useful if work with form and validations

### ISSUE THREAD

**Issue by moinkhan780** [AbdullahChauhan/custom-dropdown#23]
Feature** Will be useful if work with form and validations

Thanks!

**Comment by JesusHdez960717** [comment]
Hi @moinkhan780, the PR of this feature is in progress, but since these are big changes it takes a little time.
If need a preview version refer to the PR #20 .
Hope this help.

**Comment by TimeLord2010** [comment]
I'm trying to use the dropdown inside a Form widget, but when I try to validate the form, this widget gets flagged as failing validation.
Gonna have to drop this widget from my project all together now. :/

**Comment by AbdullahChauhan** [comment]
Hi @TimeLord2010 Which version of package are you using? Also can you please share your code for better understanding!

**Comment by AbdullahChauhan** [comment]
@moinkhan780 Form validation are now fully supported in `2.0.0`. Thanks :+1:
