### ISSUE TITLE
How to use custom model?

### ISSUE THREAD

**Issue by luis-cruzt** [AbdullahChauhan/custom-dropdown#26]
Hello, thanks for the package, I was wondering if we can use a custom model for the dropdown as now it only handles a `List<String>`, for example:

`MyModel(id: 'some-id', value: 'Kansas City')`

And then use it like:

`final list = [MyModel(id: 'some-id', value: 'Kansas City'),MyModel(id: 'some-id', value: 'Kansas City 2')]`

```
 CustomDropdown(
     items: list,
    controller: textEditingController,
),
```

And then use the `listItemBuilder`

**Comment by AbdullahChauhan** [comment]
Hi @luis-cruzt Thanks for appreciation!
The PR of this feature is in progress (PR #20). Not getting enough time to review and prepare for the release, so for now you can use this...
