### ISSUE TITLE
Textfield text 

### ISSUE THREAD

**Issue by joaothimotheo** [AbdullahChauhan/custom-dropdown#31]
Hello, How do I change the hintText of the textField, I'm Brazilian and I need to change the text from 'search' to 'pesquisar'
![image](https://github.com/AbdullahChauhan/custom-dropdown/assets/31326725/bb32c18d-7a3e-4c2f-a202-296bea2b8592)

**Comment by AbdullahChauhan** [comment]
Hey @joaothimotheo, this can't be possible in current version of the package. But I will be releasing the next version soon with a lot of new customisation options including this!

**Comment by AbdullahChauhan** [comment]
Now available in `2.0.0`. Thanks :+1:
