### ISSUE TITLE
Customize DropdownMenu border color

### ISSUE THREAD

**Issue by weluid** [AbdullahChauhan/custom-dropdown#35]
Hello, bro!
It's a usefull library.

But I have a question, is it possible to change the border color of DropdownMenu?
It would be cool to have this feature)

https://github.com/AbdullahChauhan/custom-dropdown/assets/124319560/00f5eb62-f5f9-45b0-a6fc-fbec94401572

**Comment by AbdullahChauhan** [comment]
Hey @weluid Thanks for the appreciation. 
Yes, this will be available in upcoming release of the package :rocket:

**Comment by AbdullahChauhan** [comment]
Now available in `2.0.0`. Thanks :+1:

**Comment by weluid** [comment]
Thanks!
Enjoy your day!
