### ISSUE TITLE
Hinttext is not showing

### ISSUE THREAD

**Issue by asamarsal** [AbdullahChauhan/custom-dropdown#37]
Grey Hinttext when first time before u click is not showing on my code.

child: CustomDropdown<String>(
                                            hintText: 'Select job role', // Ini adalah hintText
                                            items: statusList,
                                            initialItem: statusList.isNotEmpty ? statusList[0] : null,
                                            onChanged: (value) {
                                              log('changing value to: $value');
                                            },
                                          ),

**Comment by AbdullahChauhan** [comment]
@asamarsal Hey, I just checked and `hint`, `hintbuilder` both are working fine as expected. Can you post the complete code snippet? Also on which platform you are working?

**Comment by asamarsal** [comment]
Hello, thanks for fast respon. I test my code on android.
This is my <dropdown> :

CustomDropdown<String>(
                                            hintText: 'Select job role',
                                            items: statusList.isNotEmpty ? statusList : ['No items available'], // Provide a fallback item if the list is empty
                                            initialItem: statusList.isNotEmpty ? statusList[0] : null,
                                            onChanged: (value) {
                                              log('changing value to: $value');
                                            },
                                          ),

<My Jwt> : 
"data": [
        "Hadir",
        "Terlambat",
        "Dinas",
        "Sakit",
        "Izin"
    ]

I successful fetch the data from jwt, but hintText is not showing.

![photo1699233198](https://github.com/AbdullahChauhan/custom-dropdown/assets/34872359/832e1f81-f10d-4a96-b07c-1f2e95b0b9f7)
![photo1699233166](https://github.com/AbdullahChauhan/custom-dropdown/assets/34872359/7cb8021a-54df-4233-a518-91826d431c13)

Thanks for answer my question.

**Comment by AbdullahChauhan** [comment]
@asamarsal I can see you are providing the `initialItem` value so it's obvious that hint remains hidden because of this. The purpose of hint property is to suggest what kind of data user can select and display only when no item is selected or there's no initial item provided.

**Comment by asamarsal** [comment]
So, theres no hinttext suggest i can show when i provide initialItem? any suggestiono for me to do alternative ways? thanks

**Comment by AbdullahChauhan** [comment]
No. This is by standards. Take an example of user name text field. If the field is empty mostly we show hint text like this "Enter your user name" but if the user name already there [initialItem], why would we show the hint text? I don't think we have to, right? And even if we want to, the question is where to show hint text because the place already filled with hint text. I I hope you got my point!

**Comment by asamarsal** [comment]
okay, thanks for answer my question

**Comment by asamarsal** [comment]
Okay, thanks for answer my question
