### ISSUE TITLE
Style widget

### ISSUE THREAD

**Issue by moabdi** [AbdullahChauhan/custom-dropdown#39]
Hello,

I believe it would be beneficial to introduce additional input parameters to allow for further customization of the widget, particularly for overriding the general style. In my case, while utilizing the 'custom-dropdown' widget, I've encountered an issue where it doesn't visually integrate well with the text input theme I have already defined. It appears less representative of the intended aesthetic, especially in a dark theme context.

Moreover, I attempted to alter the filled color of the dropdown, but the changes were not reflected. This limitation restricts the ability to match the dropdown with my application's color scheme.

I am convinced that your widget could achieve greater success if it incorporated these features, providing developers with the flexibility to tailor its appearance more closely to their app's design.

Thanks in advance.

**Comment by ibrar9523** [comment]
yes just crap 
no style nothing| he should allow developer to change the colors
in my case im not able to change color of search box

**Comment by samad5353** [comment]
your library awesome please try to provide the customization of that UI so that it can match the existing projects

**Comment by AbdullahChauhan** [comment]
Hey guys @moabdi @ibrar9523 @samad5353 
This now available in `3.0.0`. You guys can check, Thanks 👍
