### ISSUE TITLE
_AnimatedSectionState#c115a(ticker active) was disposed with an active Ticker

### ISSUE THREAD

**Issue by MalikSamiAwan** [AbdullahChauhan/custom-dropdown#4]
I am using valuelistenable builder and once a value from dropdown is selected i changed the drop down to text but this is what i additionally get when onChange is called

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
_AnimatedSectionState#c115a(ticker active) was disposed with an active Ticker.

_AnimatedSectionState created a Ticker via its SingleTickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. The Ticker must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

The offending ticker was: Ticker(created by _AnimatedSectionState#c115a)
The stack trace when the Ticker was actually created was:
#0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:67:40)
#1      new Ticker (package:flutter/src/scheduler/ticker.dart:69:6)
#2      SingleTickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:198:15)
#3      new AnimationController (package:flutter/src/animation/animation_controller.dart:246:21)
#4      _AnimatedSectionState.prepareAnimations (package:animated_custom_dropdown/animated_section.dart:33:22)
#5      _AnimatedSectionState.initState (package:animated_custom_dropdown/animated_section.dart:28:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4893:57)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
...     Normal element mounting (64 frames)
#71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#72     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#73     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (63 frames)
#136    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#137    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
#139    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5845:32)
#140    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#143    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#144    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#145    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#146    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#147    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#148    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#149    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#150    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#154    _invoke (dart:ui/hooks.dart:151:10)
#155    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#156    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)

When the exception was thrown, this was the stack: 
#0      SingleTickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:209:7)
#1      SingleTickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:223:6)
#2      _AnimatedSectionState.dispose (package:animated_custom_dropdown/animated_section.dart:64:11)
#3      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4983:11)
#4      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1926:13)
#5      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#7      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#8      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#11     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#12     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#13     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#14     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#16     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#17     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#18     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#19     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#20     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#21     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#22     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#23     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#24     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#25     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#26     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#27     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#28     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#29     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#30     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#31     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#32     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#33     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#34     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#35     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#36     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#37     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#38     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#39     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#40     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#41     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#42     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6386:16)
#43     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#44     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#45     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#46     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#47     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#48     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#49     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#50     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#51     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#52     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#53     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#54     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#55     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#56     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#57     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#58     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#59     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#60     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#61     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#62     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#63     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#64     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#65     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#66     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#67     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#68     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#69     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1935:25)
#70     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2519:15)
#71     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2932:7)
#72     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:19)
#73     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#74     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#75     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#76     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#80     _invoke (dart:ui/hooks.dart:151:10)
#81     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#82     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
A OverlayEntry was used after being disposed.

Once you have called dispose() on a OverlayEntry, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:114:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:120:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:288:12)
#3      OverlayEntry._updateMounted (package:flutter/src/widgets/overlay.dart:130:5)
#4      _OverlayEntryWidgetState.dispose (package:flutter/src/widgets/overlay.dart:200:18)
#5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4983:11)
#6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1926:13)
#7      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#8      _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1935:25)
#9      BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2519:15)
#10     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2932:7)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:19)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#19     _invoke (dart:ui/hooks.dart:151:10)
#20     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#21     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================

**Comment by AbdullahChauhan** [comment]
@MalikSamiAwan Fixed in latest release. Can you please recheck and if everything works fine, close the issue. Thanks for contributing!

**Comment by NikitaBerezniki** [comment]
https://stackoverflow.com/questions/72239258/flutter-warning-operand-of-null-aware-operation-has-type-widgetsbinding

/C:/tools/flutter_sdk/.pub-cache/hosted/pub.dartlang.org/animated_custom_dropdown-1.2.1/lib/dropdown_overlay.dart:57:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/tools/flutter_sdk/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1

    WidgetsBinding.instance?.addPostFrameCallback((_) {

**Comment by MalikSamiAwan** [comment]
Thanks for replying @AbdullahChauhan i already have used some else package.
