### ISSUE TITLE
How to change color of items in the dropdown?

### ISSUE THREAD

**Issue by Besufikad17** [AbdullahChauhan/custom-dropdown#41]
Hey there, I have used `CustomDropdown` widget without `closedFillColor` and `expandedFillColor` parameters but the color of the test inside the menu is white. Is there a way to change it?

**Comment by AbdullahChauhan** [comment]
Hey @Besufikad17 
You can use `listItemBuilder` property and take full control of items customisation.

**Comment by Besufikad17** [comment]
Thanks for responding @AbdullahChauhan 
Can u provide some examples?

**Comment by ibrar9523** [comment]
Widget defaultListItemBuilder(BuildContext context, T result) {
    return Text(
      result.toString(),
      maxLines: widget.maxlines,
      overflow: TextOverflow.ellipsis,
      style: const TextStyle(fontSize: 16),
    );
  }

**Comment by Besufikad17** [comment]
Thanks a lot
