### ISSUE TITLE
Text color + icons

### ISSUE THREAD

**Issue by nikoniko2027** [AbdullahChauhan/custom-dropdown#42]
Hi! I have recently started studying flutter. I decided to use your widget to create a drop-down list. Can you tell me how I can change the style of the text inside the list? One more question. Why don't I have icons displayed?
![image](https://github.com/AbdullahChauhan/custom-dropdown/assets/38989700/d8f3e15e-1249-43e1-af79-b509ef862218)
![image](https://github.com/AbdullahChauhan/custom-dropdown/assets/38989700/45fff9d2-3323-4d9e-974f-13306baeb457)
![image](https://github.com/AbdullahChauhan/custom-dropdown/assets/38989700/52f27c1a-081b-45be-8557-3b308935888d)

**Comment by AbdullahChauhan** [comment]
Hey @nikoniko2027 
Just released `3.0.0`. Decoration support add with other new props. You can check, Thanks 👍
