### ISSUE TITLE
default margin and padding

### ISSUE THREAD

**Issue by quensh93** [AbdullahChauhan/custom-dropdown#44]
hi
how can i change default margin and padding for CustomDropdown?

![Screenshot 2023-12-06 at 12 00 13](https://github.com/AbdullahChauhan/custom-dropdown/assets/16163874/0d3425e2-4125-451a-8d9a-b356b31f956c)

**Comment by mufazmi** [comment]
Yup. Can you allow to play with margin and padding.

**Comment by 92sajid110** [comment]
I am waiting also for this.
Want to handle custom padding and margin also shadow option.
BTW after using 4-5 dropdowns packages finally i am satisfied with this package.
Thanks.

**Comment by AbdullahChauhan** [comment]
Hey everyone @quensh93 @mufazmi @92sajid110 
I'll be releasing version `2.1.0` in few days. It will include the properties related to dropdown shadow and overall paddings (header, list item, overlay) :blush:
Thanks for taking interest :thumbsup:

**Comment by 92sajid110** [comment]
We are waiting eagerly for this update.
Thanks in advance.

**Comment by arafaysaleem** [comment]
> Hey everyone @quensh93 @mufazmi @92sajid110 I'll be releasing new version in few days. It will include the properties related to dropdown shadow and overall paddings (header, list item, overlay) 😊 Thanks for taking interest 👍

The package is great and I appreciate your effort in making it better but things like this shouldn't be breaking in the first place since the package is already in 2.0.0. Suddenly all of my dropdowns UI was changed and I need to wait for the update now.

**Comment by AbdullahChauhan** [comment]
> > Hey everyone @quensh93 @mufazmi @92sajid110 I'll be releasing new version in few days. It will include the properties related to dropdown shadow and overall paddings (header, list item, overlay) 😊 Thanks for taking interest 👍
> 
> The package is great and I appreciate your effort in making it better but things like this shouldn't be breaking in the first place since the package is already in 2.0.0. Suddenly all of my dropdowns UI was changed and I need to wait for the update now.

Hey @arafaysaleem Thanks for the feedback. The things I mentioned above are not related to any fixes so shouldn't be breaking anything at all. It just customisation of this package (overall) was not made available and you may feel restricted due to this.

**Comment by AbdullahChauhan** [comment]
> > Hey everyone @quensh93 @mufazmi @92sajid110 I'll be releasing new version in few days. It will include the properties related to dropdown shadow and overall paddings (header, list item, overlay) 😊 Thanks for taking interest 👍
> 
> hey what is the expected time for this release ?? btw nice work though!!

Hey @AyushTripathi28 Thanks. Hopefully, in a day or two!

**Comment by AbdullahChauhan** [comment]
Hey guys @quensh93 @mufazmi @92sajid110 @arafaysaleem @AyushTripathi28 
Just released `3.0.0`. Lots of new changes with some breakings. You guys can check, Thanks 👍
