### ISSUE TITLE
Non-Customizable Search Bar

### ISSUE THREAD

**Issue by ParsaZa79** [AbdullahChauhan/custom-dropdown#46]
# Subject
Issue with Non-Customizable Search Bar

## Description

Dear AbdullahChauhan,

I am writing to report an issue encountered with the search bar functionality in the dropdown of your package, which I have been utilizing effectively for some time. The core of the problem lies in the search bar's lack of customizability, particularly when integrated into applications using a dark theme.

### Issue Details

**Component Affected:** Search bar in the dropdown
**Nature of Issue:** Lack of customizability in the dark theme
**Impact:** Users are unable to view the search term being typed, impairing the usability in dark-themed environments.
**Probable Cause:**
Upon investigation, I believe this issue may stem from a hardcoded fillColor value in the SeachField<T> class within your source code. This hardcoded value does not adapt well to darker themes, leading to the visibility problem described.

### Screenshot of the Issue:
![image](https://github.com/AbdullahChauhan/custom-dropdown/assets/46870036/46e15d06-add9-4ce6-a9fc-28a67aa62ff6)

### Relevant Section of the Source Code:
![image](https://github.com/AbdullahChauhan/custom-dropdown/assets/46870036/3f3fff6c-9887-47cf-b8e0-e3e14b49408c)

**Comment by AbdullahChauhan** [comment]
Hey @ParsaZa79 
Just released `3.0.0`. Dropdown decoration is now available. You can check, Thanks 👍

**Comment by ParsaZa79** [comment]
Hello dear @AbdullahChauhan,
I have just updated the plugin to the latest version and it now works perfectly. Thanks for paying attention.

**Comment by AbdullahChauhan** [comment]
Thanks. Appreciated your feedback 😊
