### ISSUE TITLE
Custom Decoration Search Dropdown

### ISSUE THREAD

**Issue by asamarsal** [AbdullahChauhan/custom-dropdown#47]
How to make decoration dropdown ("Pilih Pabrik Gula") customizable like "Tanggal" and "Masukkan Nomor Kontak" like the picture that i sent. Thanks

![photo1703727103](https://github.com/AbdullahChauhan/custom-dropdown/assets/34872359/5b135b3c-26d2-4b8f-8f24-2ec64cbfef03)

**Comment by AbdullahChauhan** [comment]
Hey @asamarsal 
Just released `3.0.0`. Dropdown decoration is now available. You can check, Thanks 👍
