### ISSUE TITLE
Need Custom Padding Attributes

### ISSUE THREAD

**Issue by chandabdullah21** [AbdullahChauhan/custom-dropdown#50]
Need these custom paddings

1. `listItemPadding: `
2. `headerPadding: `
3. `overlayOuterPadding: `

Can you please do it and update the package as soon as possible?

**Comment by AbdullahChauhan** [comment]
Hey @chandabdullah21 
These props are already available in `3.0.0`:
- `closedHeaderPadding`
- `expandedHeaderPadding`
- `listItemPadding`
- `itemsListPadding`
