### ISSUE TITLE
Disabled / read-only state

### ISSUE THREAD

**Issue by karniv00l** [AbdullahChauhan/custom-dropdown#53]
Hi,

is there any way to achieve a read-only or disabled state? I would assume that read-only state would just work as normal, but not update the value when the new option is chosen. And I'm not sure whether disabled state should fit into this library, as this could be just a collapsed input with no actions and no dropdown icon and maybe an additional styling

**Comment by KabaDH** [comment]
Hello!
[PR](https://github.com/AbdullahChauhan/custom-dropdown/pull/55)

**Comment by karniv00l** [comment]
Cool! I'm currently using `AbsorbPointer` and hiding `closedSuffixIcon` to achieve this effect

**Comment by AbdullahChauhan** [comment]
Hey @karniv00l 
Enabled/disabled feature now available in the latest release `3.1.0`. 
Thanks to @KabaDH for the contribution. Really appreciate you guys are taking interest in my package!
