### ISSUE TITLE
Scroll Controller

### ISSUE THREAD

**Issue by enes-kal** [AbdullahChauhan/custom-dropdown#54]
it is possible to add list controller to CustomDropdown<CommonItemModel>.multiSelectSearchRequest ?

What I will do

1-I will dedect bottom of listview.
2- then will get new data from endpoint.
3- then I will add new items to list

**Comment by AbdullahChauhan** [comment]
Hey @enes-kal Yeah, good idea. `listController` property will be available in the next release!

**Comment by AbdullahChauhan** [comment]
Hey @enes-kal 

`itemsListController` is now available in the latest release `3.1.0`. You can check. Thanks 😊
