### ISSUE TITLE
upgrade flutter 3.0

### ISSUE THREAD

**Issue by NikitaBerezniki** [AbdullahChauhan/custom-dropdown#6]
We can now discard the warning and wait until the authors of these packages deal with the new changes in flutter 3 to solve the problem. The developers now catching up for those changes and these should be new versions of the affected packages soon.

https://stackoverflow.com/questions/72239258/flutter-warning-operand-of-null-aware-operation-has-type-widgetsbinding

/C:/tools/flutter_sdk/.pub-cache/hosted/pub.dartlang.org/animated_custom_dropdown-1.2.1/lib/dropdown_overlay.dart:57:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.

'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/tools/flutter_sdk/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1

WidgetsBinding.instance?.addPostFrameCallback((_) {

**Comment by AbdullahChauhan** [comment]
@NikitaBerezniki Updated. Thanks for contributing!
