### ISSUE TITLE
Non-modifiable Selected Items in Dropdown

### ISSUE THREAD

**Issue by ParsaZa79** [AbdullahChauhan/custom-dropdown#63]
# Subject
Non-modifiable Selected Items in Dropdown

# Description
Dear @AbdullahChauhan,

I have created a dropdown using the multiSelectSearchRequest() factory method and encountered an issue. The problem is that I am unable to modify the selected items programmatically.

It is a common use case to allow users to clear all the selected items through an icon button or perform other modifications to the selection. However, with the current implementation, it seems that the selected items cannot be modified once they are set.

## Steps to Reproduce
1. Create a dropdown using the multiSelectSearchRequest() factory method.
2. Select one or more items in the dropdown.
3. Attempt to modify the selected items programmatically (e.g., clear the selection).
### Expected Behaviour
- I expect to be able to modify the selected items programmatically, such as clearing the selection or updating it based on certain conditions.

### Actual Behaviour
- The selected items cannot be modified programmatically. Any attempts to clear or update the selection have no effect.

# Reproduction Code
![image](https://github.com/AbdullahChauhan/custom-dropdown/assets/46870036/2998554d-35d1-41bb-9e13-95e52e135c78)

# Supporting Material
The solution to this problem is pretty straight-forward 😊. You simply have to add a property for selected item(s) in your constructors and factory methods.

Please let me know if you need any further information or clarification. Any assistance or guidance on how to resolve this issue would be greatly appreciated. 😇

**Thank you for your time and consideration. 🙏**

Best regards,
Parsa Zeinali

**Comment by AbdullahChauhan** [comment]
Hi @ParsaZa79 

Thanks very much for the details you've provided above. **Controllers** support are now available in release `3.1.0`. You can check. Thanks again 😊
