### ISSUE TITLE
why do we need to assert that `items` is not empty?

### ISSUE THREAD

**Issue by hbatalhaStch** [AbdullahChauhan/custom-dropdown#64]
In all constructors there is this assertion:
```dart
assert(items!.isNotEmpty, 'Items list must contain at least one item.',),
```
Why question is: why do we do need this? I have a case where the items come from the database and there is a high chance it might be empty so my code will be throwing whenever it returns an empty list from the database.

**Comment by AbdullahChauhan** [comment]
Hi @hbatalhaStch 
This assertion removed in latest release `3.1.0`. Thanks to you 😀
