### ISSUE TITLE
how can i clear the text already selected in drop down

### ISSUE THREAD

**Issue by samad5353** [AbdullahChauhan/custom-dropdown#67]
Hi 
need to clear the text of drop down already selected on a change of my segment control
how is that possible?

**Comment by StainsSolomonDavid** [comment]
Hi, I also have the same doubt !! If you got any Solutions.. Please Guide

**Comment by samad5353** [comment]
@AbdullahChauhan do you have any solution for this one ?

**Comment by AbdullahChauhan** [comment]
Hey there @samad5353 @StainsSolomonDavid 

Controllers support for selected items are now available in `3.1.0`. You guys can check 🙂. Thanks!
