### ISSUE TITLE
Kindly update to Flutter 3.0.1

### ISSUE THREAD

**Issue by moinkhan780** [AbdullahChauhan/custom-dropdown#7]
: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) {

**Comment by AbdullahChauhan** [comment]
@moinkhan780 Updated. Thanks for contributing!
