### ISSUE TITLE
Error message is not showing

### ISSUE THREAD

**Issue by Nihas109** [AbdullahChauhan/custom-dropdown#9]

**Comment by AbdullahChauhan** [comment]
@Nihas109 Kindly provide more details about your issue.

**Comment by Nihas109** [comment]
Can you please provide a sample code for showing error text

**Comment by AbdullahChauhan** [comment]
@Nihas109 What kind of error text?

**Comment by Nihas109** [comment]
validation errors

**Comment by AbdullahChauhan** [comment]
@Nihas109 Can you show a screenshot of the dropdown where validation errors are missing? (actually, I'm still not getting your point)!

**Comment by AbdullahChauhan** [comment]
@Nihas109

**Comment by jarvesusaram99** [comment]
I noticed that even after setting the static error text, the error message is not displaying when I select an item from the dropdown. Furthermore, when I call currentState!.validate(), it returns false, indicating that the form validation is not being performed correctly after selecting an item from the dropdown.

![image](https://user-images.githubusercontent.com/54399984/229991067-8a9a9bb2-11b0-4e94-b641-fa49597d0838.png)

**Comment by AbdullahChauhan** [comment]
@Nihas109 @jarvesusaram99 
Today, I release `2.0.0`. Can you check and confirm if your issue is resolve now?
